### ISSUE TITLE
Support both single and double quotes for string literals

### ISSUE THREAD

**Issue by MarkRobertJohnson** [RushuiGuan/expression#2]
Hello,
    I am using this expression engine for a project.  I would like to support both single and double quotes for string literals.  From what I can tell, a Parser instance can only support single or double quote string literals, but not both at the same time.  This would be a great feature to improve usability for low-skill end users.  

Thanks,
Mark

**Comment by RushuiGuan** [comment]
Thanks for the feedback.  I have created a new class SingleDoubleQuoteStringToken to address this issue.  I have also set it as the default string tokenizer for the Parser class.

**Comment by MarkRobertJohnson** [comment]
Thanks @RushuiGuan!  You are awesome!
