### ISSUE TITLE
v2.0.3 - The Add method of the IParser interface has been removed

### ISSUE THREAD

**Issue by poebrand** [RushuiGuan/expression#5]
In the release notes for v2.0.3 it mentions that "the Add method of the IParser interface has been removed". What is the workaround for this? Here is some sample code that used to work but doesn't now due to the Add method removal.

```
public IToken[] CustomTokens
{
	get; set;
}

var parser = Factory.Instance.Create();
CustomTokens.ToList().ForEach(x => parser.Add(x));
```

One of our custom tokens, for example, inherits from PrefixOperationToken.

Thanks for the help!

**Comment by RushuiGuan** [comment]
Hi Poe.  You can use the [ParserOperationAttribute](https://github.com/RushuiGuan/expression/blob/master/src/Albatross.Expression/ParserOperationAttribute.cs) on your custom class and call the Factory.Register method to register your assembly.

Here is some sample code: https://github.com/RushuiGuan/expression/blob/master/src/Albatross.Expression.Sample/CustomOperation.cs

Let me know if you have any more questions.

Regards

-Rushui
