### ISSUE TITLE
Feature Request: Allow specifying token instances in Factory.Register()

### ISSUE THREAD

**Issue by MarkRobertJohnson** [RushuiGuan/expression#6]
**Problem:**
In order to support scenarios where tokens may have external dependencies (Database, REST resources, etc.) it is necessary to use dependency injection to provide these resources in unit tests.  Currently, the Register(Assembly) method will implicitly create tokens found in the specified assemblies (types marked with [ParserOperation]).  In general, this is fine, but when unit testing operations that have external dependencies, we need to provide specific instances that have their dependencies mocked.

**Proposed Solution:**
Create a new Register(IEnumerable<IToken> tokens) method that accepts an enumerable of token instances.

**Comment by RushuiGuan** [comment]
Thanks for the input.  Do you need a release for this?

**Comment by MarkRobertJohnson** [comment]
Yes, that would be appreciated, so I can reference a new Nuget version (I assume it would be 2.0.4)

Thanks!

AXIAN
Mark Johnson
Solutions Architect
Mobile: 503.317.6381

**Comment by RushuiGuan** [comment]
2.0.4 has been deployed.
